package main

import (
	"time"

	"dawnseek.com/gin-starter/core/config"
	"dawnseek.com/gin-starter/core/handlers"
	ginzap "github.com/gin-contrib/zap"
	"github.com/gin-gonic/gin"
	_ "github.com/joho/godotenv/autoload"
	swaggerfiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	_ "dawnseek.com/gin-starter/docs" // docs is generated by Swag CLI, you have to import it.
	"go.uber.org/zap"
)

// @title Gin Swagger Example API
// @version 1.0
// @description This is a Gin Starter template for API server development
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @BasePath /
// @schemes http https
func main() {
	logger, _ := zap.NewProduction()

	router := setupRouter()

	cfg := config.LoadConfig()

	router.Use(ginzap.Ginzap(logger, time.RFC3339, true))

	router.Use(ginzap.RecoveryWithZap(logger, true))

	router.Run(cfg.ServerAddress)
}

func setupRouter() *gin.Engine {
	r := gin.Default()
	r.GET("/health-check", handlers.HandleHealthCheck)

	//For Swagger
	r.GET("/docs/*any", ginSwagger.WrapHandler(swaggerfiles.Handler))
	return r
}
