name: branch-pr

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  pr-CI:
    strategy:
      ## this will contain a matrix of all of the combinations
      ## we wish to test again:
      matrix:
        go-version: [1.19.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version

      - name: Verify dependencies
        run: go mod verify

      - name: Install swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: generate swagger doc
        run: swag init

      - name: Build
        run: go build -v ./...

      - name: Test docker images
        run: docker build -t gin-starter .
